adad = {"nova_object.version": "1.2", "nova_object.changes": ["cells"], "nova_object.name": "NUMATopology",
        "nova_object.data": {"cells": [{"nova_object.version": "1.2",
                                        "nova_object.changes": ["cpu_usage", "memory_usage", "cpuset", "pinned_cpus",
                                                                "siblings", "memory", "mempages", "id"],
                                        "nova_object.name": "NUMACell",
                                        "nova_object.data": {"cpu_usage": 8, "memory_usage": 14336,
                                                             "cpuset": [2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13],
                                                             "pinned_cpus": [4, 5, 6, 7, 10, 11, 12, 13],
                                                             "siblings": [[2], [8], [3], [9], [4], [10], [5], [11], [6],
                                                                          [12], [7], [13]], "memory": 64201,
                                                             "mempages": [{"nova_object.version": "1.1",
                                                                           "nova_object.changes": ["used", "total",
                                                                                                   "reserved",
                                                                                                   "size_kb"],
                                                                           "nova_object.name": "NUMAPagesTopology",
                                                                           "nova_object.data": {"used": 0,
                                                                                                "total": 12241340,
                                                                                                "reserved": 0,
                                                                                                "size_kb": 4},
                                                                           "nova_object.namespace": "nova"},
                                                                          {"nova_object.version": "1.1",
                                                                           "nova_object.changes": ["total", "used",
                                                                                                   "reserved",
                                                                                                   "size_kb"],
                                                                           "nova_object.name": "NUMAPagesTopology",
                                                                           "nova_object.data": {"used": 6656,
                                                                                                "total": 8192,
                                                                                                "reserved": 0,
                                                                                                "size_kb": 2048},
                                                                           "nova_object.namespace": "nova"},
                                                                          {"nova_object.version": "1.1",
                                                                           "nova_object.changes": ["used", "total",
                                                                                                   "reserved",
                                                                                                   "size_kb"],
                                                                           "nova_object.name": "NUMAPagesTopology",
                                                                           "nova_object.data": {"used": 0, "total": 0,
                                                                                                "reserved": 0,
                                                                                                "size_kb": 1048576},
                                                                           "nova_object.namespace": "nova"}], "id": 0},
                                        "nova_object.namespace": "nova"}, {"nova_object.version": "1.2",
                                                                           "nova_object.changes": ["cpu_usage",
                                                                                                   "memory_usage",
                                                                                                   "cpuset",
                                                                                                   "pinned_cpus",
                                                                                                   "siblings", "memory",
                                                                                                   "mempages", "id"],
                                                                           "nova_object.name": "NUMACell",
                                                                           "nova_object.data": {"cpu_usage": 6,
                                                                                                "memory_usage": 9216,
                                                                                                "cpuset": [14, 16, 17,
                                                                                                           18, 19, 20,
                                                                                                           22, 23, 24,
                                                                                                           25, 27],
                                                                                                "pinned_cpus": [16, 17,
                                                                                                                18, 20,
                                                                                                                25, 14],
                                                                                                "siblings": [[27], [22],
                                                                                                             [23], [16],
                                                                                                             [17], [18],
                                                                                                             [24], [19],
                                                                                                             [14], [25],
                                                                                                             [20]],
                                                                                                "memory": 64509,
                                                                                                "mempages": [{
                                                                                                                 "nova_object.version": "1.1",
                                                                                                                 "nova_object.changes": [
                                                                                                                     "used",
                                                                                                                     "total",
                                                                                                                     "reserved",
                                                                                                                     "size_kb"],
                                                                                                                 "nova_object.name": "NUMAPagesTopology",
                                                                                                                 "nova_object.data": {
                                                                                                                     "used": 0,
                                                                                                                     "total": 12320075,
                                                                                                                     "reserved": 0,
                                                                                                                     "size_kb": 4},
                                                                                                                 "nova_object.namespace": "nova"},
                                                                                                             {
                                                                                                                 "nova_object.version": "1.1",
                                                                                                                 "nova_object.changes": [
                                                                                                                     "total",
                                                                                                                     "reserved",
                                                                                                                     "size_kb",
                                                                                                                     "used"],
                                                                                                                 "nova_object.name": "NUMAPagesTopology",
                                                                                                                 "nova_object.data": {
                                                                                                                     "used": 4096,
                                                                                                                     "total": 8192,
                                                                                                                     "reserved": 0,
                                                                                                                     "size_kb": 2048},
                                                                                                                 "nova_object.namespace": "nova"},
                                                                                                             {
                                                                                                                 "nova_object.version": "1.1",
                                                                                                                 "nova_object.changes": [
                                                                                                                     "used",
                                                                                                                     "total",
                                                                                                                     "reserved",
                                                                                                                     "size_kb"],
                                                                                                                 "nova_object.name": "NUMAPagesTopology",
                                                                                                                 "nova_object.data": {
                                                                                                                     "used": 0,
                                                                                                                     "total": 0,
                                                                                                                     "reserved": 0,
                                                                                                                     "size_kb": 1048576},
                                                                                                                 "nova_object.namespace": "nova"}],
                                                                                                "id": 1},
                                                                           "nova_object.namespace": "nova"}]},
        "nova_object.namespace": "nova"}
