# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-08-06 12:59
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='case',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caseName', models.CharField(max_length=100)),
                ('caseID', models.CharField(max_length=100)),
                ('publication_date', models.DateField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='case_report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report', models.CharField(max_length=800)),
                ('id_case_report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UserSystem.case')),
            ],
        ),
        migrations.CreateModel(
            name='user_info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('safe_question', models.CharField(max_length=60)),
                ('answer', models.CharField(max_length=60)),
                ('tel', models.CharField(max_length=20)),
                ('info', models.URLField(blank=True, max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
