# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-06-20 14:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='case',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caseName', models.CharField(max_length=100)),
                ('caseID', models.CharField(max_length=100)),
                ('publication_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='case_report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report', models.CharField(max_length=800)),
            ],
        ),
        migrations.CreateModel(
            name='user',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('level', models.CharField(max_length=60)),
                ('password', models.CharField(max_length=60)),
                ('website', models.URLField()),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.AddField(
            model_name='case_report',
            name='authors',
            field=models.ManyToManyField(to='apps.user'),
        ),
        migrations.AddField(
            model_name='case_report',
            name='id_case_report',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apps.case'),
        ),
        migrations.AddField(
            model_name='case',
            name='creater',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apps.user'),
        ),
    ]
