# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-09-03 13:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='weibo_article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('article_type', models.CharField(max_length=100)),
                ('article_relation', models.CharField(max_length=100)),
                ('article_area', models.CharField(max_length=800)),
            ],
        ),
        migrations.CreateModel(
            name='weibo_comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('comment_type', models.CharField(max_length=100)),
                ('article_relation', models.CharField(max_length=100)),
                ('comment_area', models.CharField(max_length=800)),
                ('publication_date', models.DateField(blank=True)),
            ],
        ),
    ]
